### ISSUE TITLE
Upload on PyPI & repo ownership

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fpm-on-wheels#1]
Is this something we want to upload on PyPI under the name fpm we have reserved now? Also, should this repo live in Fortran-lang?

cc @gnikit @certik @milancurcic @lkedward

**Comment by gnikit** [comment]
Yes but we need to make some minor  adjustments. I have a MWE but I'll get to it when I get back to London. Is that okay?

**Comment by gnikit** [comment]
I was about to message you today.
I have a cmake build that requires a lot less boiler-plate, just a single
file.

I was planning on copying the cibuildwheel either from here or cmake.

My long term solution and a non working prototype I have was to mimic
Cargo's (I think) use of setuptools.

How do you feel about the cmake build instead of Meson?

**Comment by awvwgk** [comment]
The advantage of meson is that it is a pure Python package and simplifies installation via pip if no binary distribution is available, our only non-Python dependency would be a compiler and ninja, which are both pretty robustly handled in meson-python from my experience so far.

I don't believe that any solution in setuptools, CMake or meson will be cleaner and preferable, we are hacking around the wheel format in any case to distribute a binary on PyPI. However, I would strongly recommend against setuptools, because the compiler handling is quite difficult to get right since Fortran not being well supported there.

Feel free to share your CMake solution here and we can make a decision.

**Comment by gnikit** [comment]
I am porting things from my MWE and I will open a Draft PR.

I don't have a problem with meson (I have little experience with it though). The plan I had in mind was to use scikit-build + cmake

**Comment by gnikit** [comment]
PR #2 is in main, we have wheels for all major platforms and architectures with parallel compilation (on the fpm side), next steps should be

## Next Steps

- I will be merging this today around 14:00 GMT
- @awvwgk Can we move this repo to fortran-lang
- I will then upload the PyPi tokens and credentials
- I will backport older versions of fpm and issue releases and upload the wheels to pypi
- Issue Announcement on Discourse

**Comment by gnikit** [comment]
Gentlemen, we are live on on PyPi https://pypi.org/project/fpm/. I will make an announcement on Discourse.
I am closing this issue now, feel free to reopen if there are any issues.
